name: Test

run-name: Test:${{ github.ref_name }}(${{ github.event.head_commit.message }})

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Colcon test
        uses: miyajimad0620/traps-github-action/colcon-test@feature/colcon-test-tmp